# Site settings
title: Cidney Hamilton
email: cidney@cidneyhamilton.com
url: https://cidneyhamilton.com
description: "Cidney Hamilton's portfolio."
keywords: "game programming, portfolio, 3D, 2D"
skills: "Game Programmer - Web Developer - User Experience Designer"


# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 703269 #462045
  primary-rgb: "70,32,69"
  secondary: f0a2ee #f0a2ee
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cidney Hamilton
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: mastodon
    url: http://social.cidney.org/@cidney
  - title: facebook
    url: http://facebook.com/cidneydev
  - title: github
    url: http://github.com/cidneyhamilton

# Postal address (add as many lines as necessary)
address:
  - line: Berlin, DE 10178

# Credits content
credits: Content by Cidney Hamilton

# Build settings
markdown: kramdown
permalink: pretty

# for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
